name: Build Docker Images

on:
  push:

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        tag: [buster]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: waterlemons2k
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.tag }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/waterlemons2k/${{ github.event.repository.name }}:${{ matrix.tag }}
