name: Build Docker Images

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  define-matrix:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ env.TAGS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Define matrix
        run: echo "TAGS=$(echo */ | jq -cR 'gsub("/"; "") | split(" ")')" >>"$GITHUB_ENV"

  docker:
    runs-on: ubuntu-latest
    needs: define-matrix
    strategy:
      fail-fast: false
      matrix:
        tag: ${{ fromJSON(needs.define-matrix.outputs.tags) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: waterlemons2k
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.tag }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/waterlemons2k/${{ github.event.repository.name }}:${{ matrix.tag }}
